import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import UpProvider from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "learning app",
  description: 'Generated by create next app',
  keywords: "html,css,js,reactjs",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  return (
    <html lang="en">
      <body className={inter.className}>
        <UpProvider>{children}</UpProvider> </body>
    </html>
  )
}
